---
apiVersion: eventing.knative.dev/v1alpha1
kind: Trigger
metadata:
  name: tom-trigger
  namespace: work-conversation
spec:
  broker: conversation-broker
  filter:
    attributes:
      type: com.iancoffey.conversation.message
      subject: tom
  subscriber:
    ref:
      apiVersion: v1
      kind: Service
      name: tom

---
apiVersion: eventing.knative.dev/v1alpha1
kind: Trigger
metadata:
  name: tom-trigger-all
  namespace: work-conversation
spec:
  broker: conversation-broker
  filter:
    attributes:
      type: com.iancoffey.conversation.message
      subject: all
  subscriber:
    ref:
      apiVersion: v1
      kind: Service
      name: tom
